-- Sequence Creation for Each Table

-- Customers
CREATE SEQUENCE CUST_ID_CUST_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50000
NOCACHE
NOCYCLE;

-- Supplier
CREATE SEQUENCE SUPP_ID_SUPP_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50000
NOCYCLE
NOCACHE;

-- Company
CREATE SEQUENCE COMP_ID_COMP_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

-- Employees
CREATE SEQUENCE EMP_ID_EMP_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 5000
NOCYCLE
NOCACHE;

-- Category
CREATE SEQUENCE CAT_ID_CAT_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

-- Invoices
CREATE SEQUENCE INV_ID_INV_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50000
NOCYCLE
NOCACHE;

-- Quotation
CREATE SEQUENCE Q_ID_Q_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 50000
NOCYCLE
NOCACHE;

-- Equipment
CREATE SEQUENCE E_ID_E_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 20000
NOCYCLE
NOCACHE;
-- Purchase
CREATE SEQUENCE P_ID_P_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 50000
NOCYCLE
NOCACHE;
-- Inventory
CREATE SEQUENCE INVENTORY_ID_INVENTORY_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 20000
NOCYCLE
NOCACHE;

SELECT * FROM CAT;
CREATE TABLE CUSTOMERS(
    CUSTOMER_ID INT DEFAULT CUST_ID_CUST_TABLE.NEXTVAL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CUSTOMER_ADDRESS VARCHAR(100) NOT NULL,
    REGISTRATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CUSTOMER_TYPE VARCHAR(20) DEFAULT 'Regular' CHECK(CUSTOMER_TYPE IN('Regular', 'VIP', 'Friend'))
);

CREATE TABLE SUPPLIERS(
    SUPPLIER_ID INT DEFAULT SUPP_ID_SUPP_TABLE.NEXTVAL PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(100) NOT NULL,
    SUPPLIER_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SUPPLIER_CONTACT VARCHAR(100) NOT NULL UNIQUE,
    SUPPLIER_ADDRESS VARCHAR(100) NOT NULL
);

CREATE TABLE COMPANIES(
    COMPANY_ID INT DEFAULT COMP_ID_COMP_TABLE.NEXTVAL PRIMARY KEY,
    COMPANY_NAME VARCHAR(100) NOT NULL,
    COMPANY_TYPE VARCHAR(20) DEFAULT 'Manufacturing' CHECK(COMPANY_TYPE IN('Manufacturing', 'Industrial', 'Third Party')),
    COMPANY_CONTACT VARCHAR(15) NOT NULL UNIQUE,
    COMPANY_ADDRESS VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EMPLOYEES(
    EMPLOYEE_ID INT DEFAULT EMP_ID_EMP_TABLE.NEXTVAL PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(100) NOT NULL,
    EMPLOYEE_POSITION VARCHAR(100) NOT NULL,
    EMPLOYEE_HIRE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EMPLOYEE_SALARY VARCHAR(100) NOT NULL
);

CREATE TABLE CATEGORIES(
    CATEGORY_ID INT DEFAULT CAT_ID_CAT_TABLE.NEXTVAL PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    UNIT_OF_MEASURE VARCHAR(20) CHECK(UNIT_OF_MEASURE IN('mL', 'L', 'g', 'kg', 'lbs', 'cm', 'mm', 'm', 'inch', 'ft','packs', 'boxes', 'pieces', 'galoons')),
    DESCRIPTION VARCHAR(100)
);
CREATE TABLE QUOTATIONS(
    QUOTATION_ID INT DEFAULT Q_ID_Q_TABLE.NEXTVAL PRIMARY KEY,
    SUPPLIER_ID INT  REFERENCES SUPPLIERS(SUPPLIER_ID),
    COMPANY_ID INT REFERENCES COMPANIES(COMPANY_ID),
    EMPLOYEE_ID INT REFERENCES EMPLOYEES(EMPLOYEE_ID),
    QUOTATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATE VARCHAR(100) DEFAULT 'Confirmed' CHECK(STATE IN('Confirmed', 'Pending', 'Cancelled')),
    TOTAL INT NOT NULL
);

CREATE TABLE INVOICES(
    INVOICE_ID INT DEFAULT Q_ID_Q_TABLE.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID INT REFERENCES CUSTOMERS(CUSTOMER_ID), 
    EMPLOYEE_ID INT REFERENCES EMPLOYEES(EMPLOYEE_ID),
    QUOTATION_ID INT REFERENCES QUOTATIONS(QUOTATION_ID)
);

CREATE TABLE PURCHASES(
    PURCHASE_ID INT DEFAULT P_ID_P_TABLE.NEXTVAL PRIMARY KEY,
    SUPPLIER_ID REFERENCES SUPPLIERS(SUPPLIER_ID),
    EMPLOYEE_ID REFERENCES EMPLOYEES(EMPLOYEE_ID),
    QUOTATION_ID REFERENCES QUOTATIONS(QUOTATION_ID)
);

CREATE TABLE INVENTORY(
    INVENTORY_ID INT DEFAULT INVENTORY_ID_INVENTORY_TABLE.NEXTVAL PRIMARY KEY,
    EQ_ID INT REFERENCES EQUIPMENTS(EQ_ID),
    QUANTITY INT NOT NULL,
    LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LOCATION VARCHAR(100) NOT NULL
);

CREATE TABLE PURCHASE_DETAILS(
    PURCHASE_ID INT REFERENCES PURCHASES(PURCHASE_ID),
    EQ_ID INT REFERENCES EQUIPMENTS(EQ_ID),
    QUANTITY INT NOT NULL,
    PAYMENT_METHOD VARCHAR(20) DEFAULT 'Cash' CHECK(PAYMENT_METHOD  IN('Cash', 'Master Card', 'Debit Card', 'PayPal', 'PrePaid')),
    UNIT_COST INT NOT NULL,
    TOTAL INT NOT NULL
);

CREATE TABLE INVOICE_DETAILS(
    INVOICE_ID INT  REFERENCES INVOICES(INVOICE_ID),
    EQ_ID INT REFERENCES EQUIPMENTS(EQ_ID),
    QUANTITY INT NOT NULL,
    PAYMENT_METHOD VARCHAR(20) DEFAULT 'Cash' CHECK(PAYMENT_METHOD  IN('Cash', 'Master Card', 'Debit Card', 'PayPal', 'PrePaid')),
    PAYMENT_STATUS VARCHAR(20) DEFAULT 'Paid' CHECK(PAYMENT_STATUS  IN('Paid', 'Unpaid', 'Cancelled')),
    UNIT_PRICE INT NOT NULL,
    TOTAL INT NOT NULL
);

CREATE TABLE EQUIPMENTS(
    EQ_ID INT DEFAULT E_ID_E_TABLE.NEXTVAL PRIMARY KEY,
    EQ_NAME VARCHAR(100) NOT NULL,
    CATEGORY_ID INT REFERENCES CATEGORIES(CATEGORY_ID),
    BRAND VARCHAR(100) NOT NULL,
    MODEL VARCHAR(100) NOT NULL,
    UNIT_COST INT NOT NULL,
    SELLING_PRICE INT NOT NULL,
    DESCRIPTION VARCHAR(100)
);