


INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_EMAIL, SUPPLIER_CONTACT, SUPPLIER_ADDRESS) 
VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL, 'TechSupplies Inc.', 'contact@techsupplies.com', '555-1234', '123 Tech Rd, Silicon Valley');

INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_EMAIL, SUPPLIER_CONTACT, SUPPLIER_ADDRESS) 
VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL, 'HomeGoods Ltd.', 'support@homegoods.com', '555-5678', '456 Comfort St, Springfield');

INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_EMAIL, SUPPLIER_CONTACT, SUPPLIER_ADDRESS) 
VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL, 'AutoParts Co.', 'sales@autoparts.com', '555-2345', '789 Motor Ave, Shelbyville');

INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_EMAIL, SUPPLIER_CONTACT, SUPPLIER_ADDRESS) 
VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL, 'GreenEnergy Solutions', 'info@greenenergy.com', '555-6789', '123 Green Rd, Springfield');








INSERT INTO SUPPLIERS VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL,'SteelCorp','steel12@mail.com','121-212','Address 12');
INSERT INTO SUPPLIERS VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL,'GlassWorks','glass13@mail.com','131-313','Address 13');
INSERT INTO SUPPLIERS VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL,'AgroSupplies','agro14@mail.com','141-414','Address 14');
INSERT INTO SUPPLIERS VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL,'SolarTech','solar15@mail.com','151-515','Address 15');
INSERT INTO SUPPLIERS VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL,'CityHardware','city16@mail.com','161-616','Address 16');
INSERT INTO SUPPLIERS VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL,'WaterPro','water17@mail.com','171-717','Address 17');
INSERT INTO SUPPLIERS VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL,'SportGear','sport18@mail.com','181-818','Address 18');
INSERT INTO SUPPLIERS VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL,'TechHub','hub19@mail.com','191-919','Address 19');
INSERT INTO SUPPLIERS VALUES (SUPP_ID_SUPP_TABLE.NEXTVAL,'MegaStore','mega20@mail.com','202-020','Address 20');

INSERT INTO COMPANIES (COMPANY_ID, COMPANY_NAME, COMPANY_TYPE, COMPANY_CONTACT, COMPANY_ADDRESS) 
VALUES (COMP_ID_COMP_TABLE.NEXTVAL, 'ABC Manufacturing', 'Manufacturing', '555-1234', '123 Factory Rd, Springfield');

INSERT INTO COMPANIES (COMPANY_ID, COMPANY_NAME, COMPANY_TYPE, COMPANY_CONTACT, COMPANY_ADDRESS) 
VALUES (COMP_ID_COMP_TABLE.NEXTVAL, 'XYZ Industrial', 'Industrial', '555-5678', '456 Industrial Blvd, Shelbyville');

INSERT INTO COMPANIES (COMPANY_ID, COMPANY_NAME, COMPANY_TYPE, COMPANY_CONTACT, COMPANY_ADDRESS) 
VALUES (COMP_ID_COMP_TABLE.NEXTVAL, 'Tech Enterprises', 'Manufacturing', '555-2345', '789 Tech Ave, Springfield');

INSERT INTO COMPANIES (COMPANY_ID, COMPANY_NAME, COMPANY_TYPE, COMPANY_CONTACT, COMPANY_ADDRESS) 
VALUES (COMP_ID_COMP_TABLE.NEXTVAL, 'Green Tech Solutions', 'Industrial', '555-6789', '123 Green Rd, Springfield');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_POSITION, EMPLOYEE_SALARY) 
VALUES (EMP_ID_EMP_TABLE.NEXTVAL, 'John Carter', 'Manager', '60000');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_POSITION, EMPLOYEE_SALARY) 
VALUES (EMP_ID_EMP_TABLE.NEXTVAL, 'Sara Turner', 'Sales Associate', '45000');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_POSITION, EMPLOYEE_SALARY) 
VALUES (EMP_ID_EMP_TABLE.NEXTVAL, 'David Brown', 'Technical Lead', '75000');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_POSITION, EMPLOYEE_SALARY) 
VALUES (EMP_ID_EMP_TABLE.NEXTVAL, 'Emily White', 'Customer Support', '38000');

INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, UNIT_OF_MEASURE, DESCRIPTION) 
VALUES (CAT_ID_CAT_TABLE.NEXTVAL, 'Laptops', 'pieces', 'Personal computers designed for portability');

INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, UNIT_OF_MEASURE, DESCRIPTION) 
VALUES (CAT_ID_CAT_TABLE.NEXTVAL, 'Tablets', 'pieces', 'Portable touchscreen devices');

INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, UNIT_OF_MEASURE, DESCRIPTION) 
VALUES (CAT_ID_CAT_TABLE.NEXTVAL, 'Smartphones', 'pieces', 'Handheld communication devices');

INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, UNIT_OF_MEASURE, DESCRIPTION) 
VALUES (CAT_ID_CAT_TABLE.NEXTVAL, 'Kitchen Appliances', 'pieces', 'Various home appliances for cooking');

INSERT INTO QUOTATIONS (QUOTATION_ID, SUPPLIER_ID, COMPANY_ID, EMPLOYEE_ID, QUOTATION_DATE, STATE, TOTAL) 
VALUES (Q_ID_Q_TABLE.NEXTVAL, 1, 1, 1, CURRENT_TIMESTAMP, 'Confirmed', 1000);

INSERT INTO QUOTATIONS (QUOTATION_ID, SUPPLIER_ID, COMPANY_ID, EMPLOYEE_ID, QUOTATION_DATE, STATE, TOTAL) 
VALUES (Q_ID_Q_TABLE.NEXTVAL, 2, 2, 2, CURRENT_TIMESTAMP, 'Pending', 2000);

INSERT INTO QUOTATIONS (QUOTATION_ID, SUPPLIER_ID, COMPANY_ID, EMPLOYEE_ID, QUOTATION_DATE, STATE, TOTAL) 
VALUES (Q_ID_Q_TABLE.NEXTVAL, 3, 3, 3, CURRENT_TIMESTAMP, 'Cancelled', 1500);

INSERT INTO QUOTATIONS (QUOTATION_ID, SUPPLIER_ID, COMPANY_ID, EMPLOYEE_ID, QUOTATION_DATE, STATE, TOTAL) 
VALUES (Q_ID_Q_TABLE.NEXTVAL, 4, 4, 4, CURRENT_TIMESTAMP, 'Confirmed', 1800);

INSERT INTO INVOICES (INVOICE_ID, CUSTOMER_ID, EMPLOYEE_ID, QUOTATION_ID) 
VALUES (INV_ID_INV_TABLE.NEXTVAL, 1, 1, 1);

INSERT INTO INVOICES (INVOICE_ID, CUSTOMER_ID, EMPLOYEE_ID, QUOTATION_ID) 
VALUES (INV_ID_INV_TABLE.NEXTVAL, 2, 2, 2);

INSERT INTO INVOICES (INVOICE_ID, CUSTOMER_ID, EMPLOYEE_ID, QUOTATION_ID) 
VALUES (INV_ID_INV_TABLE.NEXTVAL, 3, 3, 3);

INSERT INTO INVOICES (INVOICE_ID, CUSTOMER_ID, EMPLOYEE_ID, QUOTATION_ID) 
VALUES (INV_ID_INV_TABLE.NEXTVAL, 4, 4, 4);


INSERT INTO PURCHASES (PURCHASE_ID, SUPPLIER_ID, EMPLOYEE_ID, QUOTATION_ID) 
VALUES (P_ID_P_TABLE.NEXTVAL, 1, 1, 1);

INSERT INTO PURCHASES (PURCHASE_ID, SUPPLIER_ID, EMPLOYEE_ID, QUOTATION_ID) 
VALUES (P_ID_P_TABLE.NEXTVAL, 2, 2, 2);

INSERT INTO PURCHASES (PURCHASE_ID, SUPPLIER_ID, EMPLOYEE_ID, QUOTATION_ID) 
VALUES (P_ID_P_TABLE.NEXTVAL, 3, 3, 3);






SELECT * FROM CAT;

SELECT * FROM INVENTORY;

-- Entry Scripts for Inventory Table



select * from equipments;
-- Entry Script for Equipments
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Digital Thermometer',12,'MedTech','DT-100',15,25,'Body temperature thermometer');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Blood Pressure Monitor',12,'Omron','BP-7',45,70,'Automatic BP monitor');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Stethoscope Pro',12,'Littmann','ST-Classic',80,120,'Professional stethoscope');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Glucometer Set',12,'Accu-Chek','GL-500',30,50,'Blood sugar testing device');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Nebulizer Compact',12,'Philips','NB-200',55,90,'Portable nebulizer');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Surgical Scissors',12,'SurgiPro','SC-12',12,20,'Stainless surgical scissors');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Medical Gloves Box',12,'SafeHands','MG-100',5,10,'100-pack latex gloves');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Pulse Oximeter',12,'OxyPlus','PO-80',25,40,'SpO2 measurement device');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Wheelchair Foldable',12,'HealthMove','WC-F1',200,280,'Foldable patient wheelchair');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'First Aid Kit',12,'LifeSaver','FAK-20',18,30,'Medical emergency kit');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Hospital Bed Electric',12,'MedEquip','HB-E2',750,1000,'Electric adjustable hospital bed');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'IV Stand Stainless',12,'Clinix','IVS-05',40,65,'IV pole stand');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Oxygen Cylinder Small',12,'AirLife','OX-10',60,90,'Portable oxygen cylinder');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'ECG Machine Portable',12,'CardioMax','ECG-300',500,650,'Portable ECG monitor');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Defibrillator AED',12,'HeartSafe','AED-100',1200,1500,'Automatic external defibrillator');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Infusion Pump',12,'CarePump','IP-50',350,480,'Intravenous infusion pump');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Ultrasound Gel 1L',12,'SonoTech','UG-1L',8,15,'Medical ultrasound gel');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Surgical Mask Box',12,'MedGuard','SM-50',4,8,'50-pack surgical masks');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Patient Monitor',12,'LifeCheck','PM-900',900,1200,'Vital signs monitoring unit');
INSERT INTO EQUIPMENTS VALUES (E_ID_E_TABLE.NEXTVAL,'Medical Syringe Pack',12,'Injecto','SY-100',6,12,'100-pack sterile syringes');