


INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 1), 100, SYSDATE, 'Kabul, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 2), 150, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 3), 200, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 4), 75, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 5), 300, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 6), 120, SYSDATE, 'Khost, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 7), 180, SYSDATE, 'Mazar-i-Sharif, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 8), 250, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 9), 90, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 10), 130, SYSDATE, 'Kabul, Afghanistan');

INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 11), 220, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 12), 160, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 13), 300, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 14), 110, SYSDATE, 'Khost, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 15), 275, SYSDATE, 'Mazar-i-Sharif, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 16), 140, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 17), 195, SYSDATE, 'Kabul, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 18), 80, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 19), 230, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 20), 150, SYSDATE, 'Balkh, Afghanistan');




INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,1,50,CURRENT_TIMESTAMP,'Main Warehouse');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,2,30,CURRENT_TIMESTAMP,'Main Warehouse');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,3,80,CURRENT_TIMESTAMP,'Storage A');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,4,20,CURRENT_TIMESTAMP,'Storage B');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,5,100,CURRENT_TIMESTAMP,'Main Warehouse');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,6,40,CURRENT_TIMESTAMP,'Storage A');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,7,12,CURRENT_TIMESTAMP,'Main Warehouse');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,8,25,CURRENT_TIMESTAMP,'Storage B');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,9,14,CURRENT_TIMESTAMP,'Storage C');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,10,60,CURRENT_TIMESTAMP,'Main Warehouse');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,11,33,CURRENT_TIMESTAMP,'Storage A');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,12,29,CURRENT_TIMESTAMP,'Storage B');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,13,18,CURRENT_TIMESTAMP,'Storage C');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,14,14,CURRENT_TIMESTAMP,'Storage A');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,15,90,CURRENT_TIMESTAMP,'Main Warehouse');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,16,100,CURRENT_TIMESTAMP,'Storage C');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,17,65,CURRENT_TIMESTAMP,'Storage B');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,18,22,CURRENT_TIMESTAMP,'Main Warehouse');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,19,17,CURRENT_TIMESTAMP,'Storage A');
INSERT INTO INVENTORY VALUES (INVENTORY_ID_INVENTORY_TABLE.NEXTVAL,20,50,CURRENT_TIMESTAMP,'Storage C');


INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 21), 180, SYSDATE, 'Kabul, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 22), 220, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 23), 150, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 24), 300, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 25), 90, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 26), 120, SYSDATE, 'Khost, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 27), 250, SYSDATE, 'Mazar-i-Sharif, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 28), 200, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 29), 170, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 30), 130, SYSDATE, 'Kabul, Afghanistan');

INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 31), 280, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 32), 95, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 33), 220, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 34), 160, SYSDATE, 'Khost, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 35), 310, SYSDATE, 'Mazar-i-Sharif, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 36), 140, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 37), 175, SYSDATE, 'Kabul, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 38), 210, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 39), 260, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 40), 190, SYSDATE, 'Balkh, Afghanistan');







INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 21), 180, SYSDATE, 'Kabul, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 22), 220, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 23), 150, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 24), 300, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 25), 90, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 26), 120, SYSDATE, 'Khost, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 27), 250, SYSDATE, 'Mazar-i-Sharif, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 28), 200, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 29), 170, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 30), 130, SYSDATE, 'Kabul, Afghanistan');

INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 31), 280, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 32), 95, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 33), 220, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 34), 160, SYSDATE, 'Khost, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 35), 310, SYSDATE, 'Mazar-i-Sharif, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 36), 140, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 37), 175, SYSDATE, 'Kabul, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 38), 210, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 39), 260, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 40), 190, SYSDATE, 'Balkh, Afghanistan');

INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 41), 150, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 42), 220, SYSDATE, 'Kabul, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 43), 180, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 44), 250, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 45), 130, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 46), 200, SYSDATE, 'Mazar-i-Sharif, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 47), 170, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 48), 190, SYSDATE, 'Khost, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 49), 210, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 50), 140, SYSDATE, 'Kabul, Afghanistan');

INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 51), 300, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 52), 160, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 53), 180, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 54), 220, SYSDATE, 'Mazar-i-Sharif, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 55), 140, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 56), 250, SYSDATE, 'Khost, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 57), 190, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 58), 210, SYSDATE, 'Kabul, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 59), 175, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 60), 230, SYSDATE, 'Kandahar, Afghanistan');




INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 61), 160, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 62), 200, SYSDATE, 'Mazar-i-Sharif, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 63), 180, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 64), 220, SYSDATE, 'Khost, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 65), 140, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 66), 250, SYSDATE, 'Kabul, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 67), 190, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 68), 210, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 69), 175, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 70), 230, SYSDATE, 'Mazar-i-Sharif, Afghanistan');

INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 71), 150, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 72), 200, SYSDATE, 'Khost, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 73), 180, SYSDATE, 'Jalalabad, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 74), 220, SYSDATE, 'Kabul, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 75), 140, SYSDATE, 'Herat, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 76), 250, SYSDATE, 'Kandahar, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 77), 190, SYSDATE, 'Balkh, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 78), 210, SYSDATE, 'Mazar-i-Sharif, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 79), 175, SYSDATE, 'Ghazni, Afghanistan');
INSERT INTO INVENTORY VALUES (INV_ID_INV_TABLE.NEXTVAL, (SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 80), 230, SYSDATE, 'Khost, Afghanistan');


