

INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 1), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 1), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 1));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 2), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 2), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 2));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 3), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 3), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 3));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 4), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 4), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 4));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 5), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 5), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 5));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 6), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 6), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 6));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 7), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 7), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 7));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 8), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 8), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 8));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 9), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 9), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 9));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 10), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 10), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 10));

INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 11), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 11), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 11));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 12), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 12), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 12));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 13), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 13), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 13));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 14), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 14), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 14));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 15), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 15), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 15));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 16), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 16), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 16));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 17), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 17), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 17));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 18), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 18), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 18));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 19), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 19), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 19));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 20), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 20), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 20));











INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 21), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 21), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 21));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 22), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 22), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 22));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 23), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 23), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 23));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 24), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 24), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 24));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 25), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 25), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 25));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 26), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 26), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 26));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 27), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 27), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 27));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 28), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 28), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 28));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 29), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 29), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 29));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 30), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 30), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 30));

INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 31), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 31), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 1));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 32), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 32), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 2));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 33), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 33), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 3));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 34), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 34), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 4));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 35), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 35), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 5));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 36), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 36), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 6));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 37), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 37), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 7));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 38), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 38), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 8));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 39), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 39), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 9));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 40), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 40), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 10));

INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 41), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 41), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 11));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 42), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 42), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 12));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 43), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 43), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 13));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 44), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 44), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 14));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 45), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 45), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 15));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 46), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 46), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 16));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 47), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 47), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 17));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 48), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 48), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 18));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 49), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 49), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 19));
INSERT INTO INVOICES VALUES(INV_ID_INV_TABLE.nextval,(SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_ID = 50), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 50), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 20));




select * from invoices;





select * from purchases;
insert into purchases values(P_ID_P_TABLE.nextval, (select supplier_id from suppliers where supplier_id = 1), (select employee_id from employees where employee_id = 1), (select quotation_id from quotations where quotation_id = 1));
select * from purchases;
describe purchases;




select * from cat;



INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 1), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 1), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 1));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 2), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 2), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 2));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 3), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 3), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 3));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 4), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 4), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 4));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 5), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 5), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 5));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 6), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 6), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 6));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 7), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 7), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 7));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 8), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 8), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 8));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 9), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 9), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 9));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 10), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 10), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 10));

INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 11), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 11), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 11));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 12), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 12), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 12));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 13), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 13), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 13));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 14), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 14), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 14));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 15), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 15), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 15));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 16), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 16), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 16));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 17), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 17), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 17));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 18), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 18), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 18));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 19), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 19), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 19));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 20), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 20), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 20));


select * from purchases;


INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 21), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 21), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 21));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 22), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 22), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 22));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 23), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 23), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 23));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 24), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 24), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 24));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 25), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 25), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 25));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 26), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 26), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 26));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 27), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 27), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 27));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 28), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 28), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 28));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 29), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 29), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 29));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 30), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 30), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 30));

INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 31), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 31), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 31));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 32), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 32), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 32));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 33), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 33), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 33));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 34), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 34), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 34));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 35), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 35), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 35));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 36), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 36), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 36));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 37), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 37), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 37));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 38), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 38), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 38));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 39), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 39), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 39));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 40), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 40), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 40));

-- wrap quotation IDs back to 1–10 for next batch
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 41), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 41), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 1));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 42), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 42), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 2));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 43), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 43), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 3));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 44), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 44), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 4));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 45), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 45), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 5));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 46), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 46), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 6));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 47), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 47), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 7));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 48), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 48), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 8));
INSERT INTO PURCHASES VALUES(P_ID_P_TABLE.nextval,(SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 49), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 49), (SELECT QUOTATION_ID FROM QUOTATIONS WHERE QUOTATION_ID = 9));





insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 31), (select EQ_ID from equipments where EQ_ID = 31), 12, 'Master Card', 950);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 32), (select EQ_ID from equipments where EQ_ID = 32), 18, 'Credit Card', 1200);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 33), (select EQ_ID from equipments where EQ_ID = 33), 20, 'Debit Card', 800);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 34), (select EQ_ID from equipments where EQ_ID = 34), 25, 'Paypal', 600);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 35), (select EQ_ID from equipments where EQ_ID = 35), 10, 'PrePaid', 1500);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 36), (select EQ_ID from equipments where EQ_ID = 36), 14, 'Cash', 1100);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 37), (select EQ_ID from equipments where EQ_ID = 37), 16, 'Master Card', 700);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 38), (select EQ_ID from equipments where EQ_ID = 38), 22, 'Credit Card', 950);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 39), (select EQ_ID from equipments where EQ_ID = 39), 19, 'Debit Card', 1250);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 40), (select EQ_ID from equipments where EQ_ID = 40), 21, 'Paypal', 500);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 41), (select EQ_ID from equipments where EQ_ID = 41), 13, 'PrePaid', 1350);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 42), (select EQ_ID from equipments where EQ_ID = 42), 17, 'Cash', 900);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 43), (select EQ_ID from equipments where EQ_ID = 43), 15, 'Master Card', 1000);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 44), (select EQ_ID from equipments where EQ_ID = 44), 20, 'Credit Card', 750);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 45), (select EQ_ID from equipments where EQ_ID = 45), 18, 'Debit Card', 1400);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 46), (select EQ_ID from equipments where EQ_ID = 46), 24, 'Paypal', 650);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 47), (select EQ_ID from equipments where EQ_ID = 47), 11, 'PrePaid', 1600);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 48), (select EQ_ID from equipments where EQ_ID = 48), 9, 'Cash', 2000);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 49), (select EQ_ID from equipments where EQ_ID = 49), 14, 'Master Card', 850);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 50), (select EQ_ID from equipments where EQ_ID = 50), 12, 'Credit Card', 1250);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 51), (select EQ_ID from equipments where EQ_ID = 51), 20, 'Debit Card', 950);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 52), (select EQ_ID from equipments where EQ_ID = 52), 22, 'Paypal', 700);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 53), (select EQ_ID from equipments where EQ_ID = 53), 16, 'PrePaid', 1150);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 54), (select EQ_ID from equipments where EQ_ID = 54), 18, 'Cash', 1300);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 55), (select EQ_ID from equipments where EQ_ID = 55), 25, 'Master Card', 600);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 56), (select EQ_ID from equipments where EQ_ID = 56), 30, 'Credit Card', 450);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 57), (select EQ_ID from equipments where EQ_ID = 57), 12, 'Debit Card', 1500);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 58), (select EQ_ID from equipments where EQ_ID = 58), 14, 'Paypal', 1100);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 59), (select EQ_ID from equipments where EQ_ID = 59), 20, 'PrePaid', 950);

insert into purchase_details
(PURCHASE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_COST)
values((select purchase_id from purchases where purchase_id = 60), (select EQ_ID from equipments where EQ_ID = 60), 22, 'Cash', 800);
























SELECT * FROM INVOICE_DETAILS;

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM  INVOICES WHERE INVOICE_ID = 1),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 1), 20, 'Master Card', 15000);
ALTER TABLE INVOICE_DETAILS
ADD (TOTAL GENERATED ALWAYS AS (QUANTITY * UNIT_PRICE) VIRTUAL);





INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 1),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 1), 20, 'Master Card', 15000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 2),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 2), 15, 'Credit Card', 12000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 3),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 3), 10, 'Debit Card', 9500);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 4),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 4), 25, 'Paypal', 8000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 5),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 5), 30, 'PrePaid', 6000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 6),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 6), 12, 'Cash', 18000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 7),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 7), 18, 'Master Card', 11000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 8),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 8), 22, 'Credit Card', 9500);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 9),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 9), 14, 'Debit Card', 12500);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 10),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 10), 16, 'Paypal', 9000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 11),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 11), 20, 'PrePaid', 7000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 12),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 12), 8, 'Cash', 25000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 13),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 13), 6, 'Master Card', 32000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 14),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 14), 9, 'Credit Card', 18000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 15),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 15), 11, 'Debit Card', 9500);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 16),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 16), 13, 'PayPal', 6000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 17),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 17), 17, 'PrePaid', 7500);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 18),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 18), 19, 'Cash', 8500);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 19),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 19), 21, 'Master Card', 4000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 20),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 20), 23, 'Credit Card', 3000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 21),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 21), 15, 'Debit Card', 12000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 22),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 22), 18, 'PayPal', 9500);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 23),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 23), 20, 'PrePaid', 7000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 24),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 24), 25, 'Cash', 5000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 25),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 25), 30, 'Master Card', 4500);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 26),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 26), 12, 'Credit Card', 15000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 27),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 27), 14, 'Debit Card', 11000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 28),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 28), 16, 'PayPal', 9000);

INSERT INTO INVOICE_DETAILS (INVOICE_ID, EQ_ID, QUANTITY, PAYMENT_METHOD, UNIT_PRICE)
VALUES((SELECT INVOICE_ID FROM INVOICES WHERE INVOICE_ID = 29),(SELECT EQ_ID FROM EQUIPMENTS WHERE EQ_ID = 29), 18, 'PrePaid', 8000);
