












INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 1), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 2), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 3), SYSDATE, 'Confirmed', 350000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 2), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 4), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 5), SYSDATE, 'Pending', 420000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 3), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 6), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 7), SYSDATE, 'Cancelled', 280000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 4), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 8), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 9), SYSDATE, 'Confirmed', 500000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 5), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 10), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 11), SYSDATE, 'Pending', 310000);

INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 6), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 12), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 13), SYSDATE, 'Confirmed', 275000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 7), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 14), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 15), SYSDATE, 'Cancelled', 480000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 8), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 16), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 17), SYSDATE, 'Pending', 330000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 9), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 18), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 19), SYSDATE, 'Confirmed', 600000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 10), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 20), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 21), SYSDATE, 'Confirmed', 450000);

INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 11), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 22), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 23), SYSDATE, 'Pending', 390000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 12), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 24), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 25), SYSDATE, 'Confirmed', 340000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 13), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 26), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 27), SYSDATE, 'Cancelled', 410000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 14), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 28), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 29), SYSDATE, 'Confirmed', 360000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 15), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 30), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 31), SYSDATE, 'Pending', 320000);

INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 16), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 32), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 33), SYSDATE, 'Confirmed', 550000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 17), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 34), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 35), SYSDATE, 'Cancelled', 295000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 18), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 36), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 37), SYSDATE, 'Pending', 370000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 19), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 38), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 39), SYSDATE, 'Confirmed', 480000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 20), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 40), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 41), SYSDATE, 'Confirmed', 510000);




















INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 2), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 3), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 2), SYSDATE, 'Confirmed', 330000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 4), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 5), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 4), SYSDATE, 'Pending', 290000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 6), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 7), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 6), SYSDATE, 'Cancelled', 410000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 8), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 9), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 8), SYSDATE, 'Confirmed', 460000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 10), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 11), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 10), SYSDATE, 'Pending', 320000);

INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 12), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 13), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 12), SYSDATE, 'Confirmed', 375000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 14), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 15), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 14), SYSDATE, 'Cancelled', 440000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 16), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 17), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 16), SYSDATE, 'Pending', 285000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 18), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 19), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 18), SYSDATE, 'Confirmed', 500000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 20), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 21), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 20), SYSDATE, 'Confirmed', 390000);

INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 3), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 22), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 22), SYSDATE, 'Pending', 310000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 5), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 23), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 24), SYSDATE, 'Confirmed', 455000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 7), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 25), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 26), SYSDATE, 'Cancelled', 420000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 9), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 27), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 28), SYSDATE, 'Pending', 365000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 11), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 29), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 30), SYSDATE, 'Confirmed', 480000);

INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 13), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 31), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 32), SYSDATE, 'Confirmed', 350000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 15), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 33), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 34), SYSDATE, 'Cancelled', 405000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 17), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 35), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 36), SYSDATE, 'Pending', 330000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 19), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 37), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 38), SYSDATE, 'Confirmed', 520000);
INSERT INTO QUOTATIONS VALUES (Q_ID_Q_TABLE.nextval, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_ID = 1), (SELECT COMPANY_ID FROM COMPANIES WHERE COMPANY_ID = 39), (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 40), SYSDATE, 'Confirmed', 470000);




